export const wordsDataService = () => {
    return [
        { id: 1, word: "Anillo", rimas: 2, syllable_separation: "a-ni-llo", image: "https://drive.google.com/uc?id=18xKt0tfNCNN42OzxqzuIZS9qCknbgfoX" , audio: "https://drive.google.com/uc?id=1AWaPpcgvnAx7xIw1sjdI_YZVor9R7c32", audioSilaba: "https://drive.google.com/uc?id=1_uL63Sg_nHt2VE6XktCbEPrEHcZ3Q7-6" },
        { id: 2, word: "Martillo", rimas: 1, syllable_separation: "mar-ti-llo", image: "https://drive.google.com/uc?id=1NZaVQtckGoVb6ppATEHT6H4POMWHpUbg", audio: "https://drive.google.com/uc?id=1R5qgjqOV4tfdUTwBl89NAvh4-O5r4Z5E", audioSilaba: "https://drive.google.com/uc?id=1VfSv6UVcIkPumNIqhHyJwowaX1NZYlNy" },
        { id: 3, word: "Araña", rimas: 4, syllable_separation: "a-ra-ña", image: "https://drive.google.com/uc?id=1GV25qVE5Lmi--Ua2RAvgS1vXMTfpu01f", audio: "https://drive.google.com/uc?id=1c-w_RYAiO9zb3DTBs6JSY9lnN_BzqpWY", audioSilaba: "https://drive.google.com/uc?id=1p6GTDNt39vz_0yW3b2qFA0kuB5GdPxMv" },
        { id: 4, word: "Montaña", rimas: 3, syllable_separation: "mon-ta-ña", image: "https://drive.google.com/uc?id=1GEKUDteP6QoFkSUKzN-gwfNtrRx5sa-O", audio: "https://drive.google.com/uc?id=14zwhMtAtgQ_qrc-KINd6RwzOSJcmrb08", audioSilaba: "https://drive.google.com/uc?id=1AmVyV33Ge_9D6PC3BIrt-NeV6Aa8Ir6T" },
        { id: 5, word: "Ardilla", rimas: 6, syllable_separation: "ar-di-lla", image: "https://drive.google.com/uc?id=1VXw3FnqaglDW2BgwefRNzzxyYl_5zrae", audio: "https://drive.google.com/uc?id=1rbf7UBD92HoL7AzYUXa384SMBO_P0Qkv", audioSilaba: "https://drive.google.com/uc?id=1bkCtjkIf2LMQGVc6o5a2ozUyTxjrytvq" },
        { id: 6, word: "Silla", rimas: 5, syllable_separation: "si-lla", image: "https://drive.google.com/uc?id=1cx0S9njGh7_h_XiP8iSx7AqcOmy4kmaU", audio: "https://drive.google.com/uc?id=1ZBERbOg1JdmqpexF2ZTRuIsc0yCPnnG_", audioSilaba: "https://drive.google.com/uc?id=159wlPtZBkZurItd0qQ0ykT7czB4efTS8" },
        { id: 7, word: "Ballena", rimas: 8, syllable_separation: "ba-lle-na", image: "https://drive.google.com/uc?id=1ubv3NHD486GVjKYcFUABA9v0Uf-bs6YR", audio: "https://drive.google.com/uc?id=1cnJbiDCH_06O4S7-SN1N7GAVpS7-1xFJ", audioSilaba: "https://drive.google.com/uc?id=1yoyb8JD3XVsWeZt0oLG5tlqhCYhZYblx" },
        { id: 8, word: "Sirena", rimas: 7, syllable_separation: "si-re-na", image: "https://drive.google.com/uc?id=1MenlVBOK78xpUuDKOpuKtCDjE3j4Dcce", audio: "https://drive.google.com/uc?id=1zaLAlxWpOP7ggox44oOTze0dBfRt7sgB", audioSilaba: "https://drive.google.com/uc?id=1o1FFE2JbaS4gugMc1pfrd4ooJI-1-6aV" },
        { id: 9, word: "Botella", rimas: 10, syllable_separation: "bo-te-lla", image: "https://drive.google.com/uc?id=1meDu2clpV1NgxG1Q4WEAzzs_xnSY3dqd", audio: "https://drive.google.com/uc?id=1fYDoNsiMly9ZWEQUlHKdWWVadoPeCRqW", audioSilaba: "https://drive.google.com/uc?id=1roxyMy-rlQjp3WnwstIzbse66mgU2GUR" },
        { id: 10, word: "Estrella", rimas: 9, syllable_separation: "es-tre-lla", image: "https://drive.google.com/uc?id=19iiMVAKZeU18at7kzJGx651wyqTryyE-", audio: "https://drive.google.com/uc?id=1OBar7xridqEbP-VsZN3AfCc12GN7ELya", audioSilaba: "https://drive.google.com/uc?id=1wJmS04yJ-a0cy5Kc-4Pb9SG521XiTb3n" },
        { id: 11, word: "Casa", rimas: 12, syllable_separation: "ca-sa", image: "https://drive.google.com/uc?id=11J-DDHkRsJyPw9SKhM0Kw5ZzG3dlHYPS" , audio:  "https://drive.google.com/uc?id=1b05JJI3FZuRcNjEWsM7d8m51K7oRv4yx",  audioSilaba: "https://drive.google.com/uc?id=1rLxgY9SdDcL72RQvHfyFmshwJVapSieI" },
        { id: 12, word: "Masa", rimas: 11, syllable_separation: "ma-sa", image: "https://drive.google.com/uc?id=1TM4eHRdsNs_h12RMuLbFFLmlmXbbrvS2", audio: "https://drive.google.com/uc?id=1ZuqJ1ElWFfqshFtHfiKX9yIfGzli-TT6",  audioSilaba: "https://drive.google.com/uc?id=1DpdItD9GaqaPhasB0FsJqFbn_Lv9Aqsy" },
        { id: 13, word: "Conejo", rimas: 14, syllable_separation: "co-ne-jo", image: "https://drive.google.com/uc?id=16LSS-UXYbPonoEtEtnZAdRMk3S5xFtpf", audio: "https://drive.google.com/uc?id=1Dx-N8My3far9jcWb5tKeTSLOIuOez0wK", audioSilaba: "https://drive.google.com/uc?id=17FOV56XL-pih3dOZDBDyOVeKYTFJMofi" },
        { id: 14, word: "Cangrejo", rimas: 13, syllable_separation: "can-gre-jo", image: "https://drive.google.com/uc?id=1pJMfNl9zpUFbiCmrdwbie9WyO-d3VEBT", audio: "https://drive.google.com/uc?id=1ecpelX5Z1usn-SYrDlqLS4zXOtKqDUFF", audioSilaba: "https://drive.google.com/uc?id=15lacvH1Z6ctykpj4iuPs7sLIaWgxlDCz" },
        { id: 15, word: "Cuna", rimas: 16, syllable_separation: "cu-na", image: "https://drive.google.com/uc?id=1dwbuUkw_5953ddiV_Fsrkwa9FpMcIw44", audio: "https://drive.google.com/uc?id=17nKkK8wLTBP2aNru_k2bLJLEKQpJCL-Y", audioSilaba: "https://drive.google.com/uc?id=1H-UnbLi2e17N99GteZGdOKmKhOc-Yajo" },
        { id: 16, word: "Luna", rimas: 15, syllable_separation: "lu-na", image: "https://drive.google.com/uc?id=1R_hqFSudvLRQalLs7cGgqowsr9aIGhaS", audio: "https://drive.google.com/uc?id=1QKEEZIVRsI971x1a4jn6tCs6_e1PeyTn", audioSilaba: "https://drive.google.com/uc?id=10gqaGG2kMYLZXIAjVVg1VUBUs75w5qa3" },
        { id: 17, word: "Gato", rimas: 18, syllable_separation: "ga-to", image: "https://drive.google.com/uc?id=1WtiUrRGzZOhP2Hbm7VrO5q2PpOl-2cDd" , audio: "https://drive.google.com/uc?id=1Mcxa_4BMQE4IndE54vNrn8rYfwUemWPe", audioSilaba: "https://drive.google.com/uc?id=1hO6PxQHHZh1sNrnaWBUV5zph_h-apsS7" },
        { id: 18, word: "Zapato", rimas: 17, syllable_separation: "za-pa-to", image: "https://drive.google.com/uc?id=1LaXHD6PbyK4aZ_bcM50ldw5MFai6wGYm", audio: "https://drive.google.com/uc?id=1edTpQOI8V6R-psvN2Psk-T-v7JCrBket", audioSilaba: "https://drive.google.com/uc?id=1f0xJHy9kBa0VmnfHx0xlNaBy3KvlOSbp" },
        { id: 19, word: "León", rimas: 20, syllable_separation: "le-ón", image: "https://drive.google.com/uc?id=1Mx4j16FAnj1_W-DePhqCd0XMdwtb-lai", audio: "https://drive.google.com/uc?id=1qT8CbHSa1QWWQL3D323wZqhGPjFTbKdp", audioSilaba: "https://drive.google.com/uc?id=1UblVYr5jM-VMpxAPSqDO1FHoicQpcaVF" },
        { id: 20, word: "Avión", rimas: 19, syllable_separation: "a-vión", image: "https://drive.google.com/uc?id=1ilgG4xXvM3sUtxbVW-OfmvMIINM7LChe", audio: "https://drive.google.com/uc?id=1TEx6m4AHLEEK19vIfDsDjaQ5tShJFXQa", audioSilaba: "https://drive.google.com/uc?id=1AMLkVYlgqtbcf5ftbWdt1eCeZnfDVyjv" },
        { id: 21, word: "Mago", rimas: 22, syllable_separation: "ma-go", image: "https://drive.google.com/uc?id=18BjPFXhlkv7OhO3Fe16l2K7wcxPnk46n" , audio: "https://drive.google.com/uc?id=1F_psExyi6BFY4m1ctZTtFp0IUZOwHcCl", audioSilaba: "https://drive.google.com/uc?id=1A68MLWgFK9MmPZJSfMIGXTgyec0a7tpM" },
        { id: 22, word: "Lago", rimas: 21, syllable_separation: "la-go", image: "https://drive.google.com/uc?id=1U4-6kqwS3vYszmFpA0mbQH-Lghr2it6t", audio: "https://drive.google.com/uc?id=1R1GMtB7AdnGetXCpjG6sYkluc_mnnd5F", audioSilaba: "https://drive.google.com/uc?id=1b-Z6NSkjCWUGe2g_VUWvpoYOtFtM8dp3" },
        { id: 23, word: "Maleta", rimas: 24, syllable_separation: "ma-le-ta", image: "https://drive.google.com/uc?id=1aM46_D02cOW1qXkYlay5xU6GbGhCrzxK" , audio: "https://drive.google.com/uc?id=1zFWBTXne09XJjuv5pFiPdx9zYXI1xBKv", audioSilaba: "https://drive.google.com/uc?id=12qHbQu_FV8XNGzheBfJkkdmKRuZ1E6-l" },
        { id: 24, word: "Paleta", rimas: 23, syllable_separation: "pa-le-ta", image: "https://drive.google.com/uc?id=10ytLUEA9TxRhaE8Jbg7Q-FLOZv-jAB5D", audio: "https://drive.google.com/uc?id=1clrBI35rO9CXsdmJd2tryKGX8Qf6bpTc", audioSilaba: "https://drive.google.com/uc?id=1IoWEpwGNAnxHpYEC4SMT4SUqRcAsiF9W" },
        { id: 25, word: "Marcador", rimas: 26, syllable_separation: "mar-ca-dor", image: "https://drive.google.com/uc?id=1CXFCLa8qtl6QYIX3PdB6_jPsWxz7CGuv", audio: "https://drive.google.com/uc?id=1GFlUMApCWyfq4vZICaFT_RTVJza0ssat", audioSilaba: "https://drive.google.com/uc?id=1wTPOzjETeRsvI2pjLZCB5Q4qi8pOg30I" },
        { id: 26, word: "Borrador", rimas: 25, syllable_separation: "bor-ra-dor", image: "https://drive.google.com/uc?id=1Gtrsr3bw9lC_aKvWIOgn3kYep-V6E7Cc", audio: "https://drive.google.com/uc?id=10EXl8-OxraI6o3VPT5-bT_N7iEEQStTE", audioSilaba: "https://drive.google.com/uc?id=19MYFyuWLgYcS0CtNAlnoRFhfOY-HRb-B" },
        { id: 27, word: "Muela", rimas: 28, syllable_separation: "mue-la", image: "https://drive.google.com/uc?id=1KPJ1ZeF91FJdCfHFfB-gPr6DT7rB6v3b", audio: "https://drive.google.com/uc?id=191dRaypN9mK6ufIzkV4Oz8qua6UaT_BY", audioSilaba: "https://drive.google.com/uc?id=1ING4KRtZhH24tA8hfKa5dCTti7T9zxA8" },
        { id: 28, word: "Escuela", rimas: 27, syllable_separation: "es-cue-la", image: "https://drive.google.com/uc?id=17qBapI01u8P-UElKQlCIEt8qG1wW_7UJ", audio: "https://drive.google.com/uc?id=1G-UhgrsKtLAdroMYLJBq8mdi_yJPCnsX", audioSilaba: "https://drive.google.com/uc?id=1HpguDD1fbCXUNbj5ShXp2dTo-l1Kxibc" },
        { id: 29, word: "Oruga", rimas: 30, syllable_separation: "o-ru-ga", image: "https://drive.google.com/uc?id=1UWX2HM9xQvwX4s8ZFEZr9IrzaxJ9w9JG", audio: "https://drive.google.com/uc?id=1JkJj6PXY7pJ3-pUQieY4hzRrpl3goRT0", audioSilaba: "https://drive.google.com/uc?id=1WANq1BIJlSoBwqrrQUmN3J1bUVtEwtkk" },
        { id: 30, word: "Tortuga", rimas: 29, syllable_separation: "tor-tu-ga", image: "https://drive.google.com/uc?id=10rMhEw_a_wKESv8CN3HnNRRKdH74qa2q", audio: "https://drive.google.com/uc?id=1Th5q90dpvcyea5-Pv3lzMhN77WJhBvM3", audioSilaba: "https://drive.google.com/uc?id=1XNFnEgF5cDVr8K4tCbCgNkFhoBKKgQVU" },
        { id: 31, word: "Oveja", rimas: 32, syllable_separation: "o-ve-ja", image: "https://drive.google.com/uc?id=1TrJ1_VSBWi4jCnMnZS717G4uItswYhMy", audio: "https://drive.google.com/uc?id=16fxO-axjiehPSFoPpVJ1F9LCwryJ6euX", audioSilaba: "https://drive.google.com/uc?id=1V9UFQWUpkgZlokm9UHSBZjSB8UX-D97U" },
        { id: 32, word: "Abeja", rimas: 31, syllable_separation: "a-be-ja", image: "https://drive.google.com/uc?id=17AaRM9jkkq-2rSZE2cdmAl4ltp7YVWW8", audio: "https://drive.google.com/uc?id=18opwf6sXFk7s1YQ16lw8o_Ai-NJVzoIH", audioSilaba: "https://drive.google.com/uc?id=19G4li1KbuzEowp82ga2uGFFIGtPR7dJQ" },
        { id: 33, word: "Piña", rimas: 34, syllable_separation: "pi-ña", image: "https://drive.google.com/uc?id=1OXmcnladlflCDKk_Qva1DZ5R0ell05H1", audio: "https://drive.google.com/uc?id=118UID0qTb3LRKP38XpxhrBMdtAsdtWRq", audioSilaba: "https://drive.google.com/uc?id=1nxraBGhTqOF3zsFfSr4NHzRybuNryMOT" },
        { id: 34, word: "Niña", rimas: 33, syllable_separation: "ni-ña", image: "https://drive.google.com/uc?id=1mHdTSnYDzAsK9qN8HcALGqHY_L73baQD", audio: "https://drive.google.com/uc?id=13B9aGCco0JEZSUMItRph1zg6Pi9NTXQP", audioSilaba: "https://drive.google.com/uc?id=1UPx1enCofx2CkPI6vosDLrl9SDuseFuJ" },
        { id: 35, word: "Plato", rimas: 36, syllable_separation: "pla-to", image: "https://drive.google.com/uc?id=1iREStqyNI8Z3mLosacLwgPSY2rdUv968", audio: "https://drive.google.com/uc?id=1VTwncmeH2K6vWTY7Nr0fz1Mi-OVOIGin", audioSilaba: "https://drive.google.com/uc?id=1wK1MdhBvW2cmVmfSjw19o029wDAynOVk" },
        { id: 36, word: "Pato", rimas: 35, syllable_separation: "pa-to", image: "https://drive.google.com/uc?id=1PJKa48pp9yU1dfB7LIghpCPCsCpEioZ2", audio: "https://drive.google.com/uc?id=1XgyY07oTCYB9xsE5uAuxzg7o5JjTfYvZ", audioSilaba: "https://drive.google.com/uc?id=105GQe0VbkDhSMXDI-h1UKpKYM_EaLKIf" },
        { id: 37, word: "Queso", rimas: 38, syllable_separation: "que-so", image: "https://drive.google.com/uc?id=1bRMFblsFq8c18zVHPWSfCFB0Y2JIVmni", audio: "https://drive.google.com/uc?id=1EC5vwFUll5IYHDyehmuanf8CssrdRBl_", audioSilaba: "https://drive.google.com/uc?id=1QqWHixto515TvKjm1GM4M1EnG4lbrlCq" },
        { id: 38, word: "Hueso", rimas: 37, syllable_separation: "hue-so", image: "https://drive.google.com/uc?id=1fuQwGHoWyFhtrqEkzVzfawS3sHgVchxR", audio: "https://drive.google.com/uc?id=1arVbAieyFVbuk54h2SqYZEMtSBEUZOGO", audioSilaba: "https://drive.google.com/uc?id=1sxYugFBz1PbaNDRReFDjO3Y1BmblZceC" },
        { id: 39, word: "Rana", rimas: 40, syllable_separation: "ra-na", image: "https://drive.google.com/uc?id=1_HsvdbeYB0IHDmRPmNj_RVdvht99wtxL", audio: "https://drive.google.com/uc?id=18RHy8LWBvXxXxb-30xg68acyt63YPWX_", audioSilaba: "https://drive.google.com/uc?id=1V81byWfV1dudMrHORDOFw-hSYOqe7nTj" },
        { id: 40, word: "Banana", rimas: 39, syllable_separation: "ba-na-na", image: "https://drive.google.com/uc?id=16OZ5lHur0ac15FAZ1JCwe7RJIYSYNFDH", audio: "https://drive.google.com/uc?id=1ihwl5lYamCYP6Le6eKEDfH-TD_-C97k0", audioSilaba: "https://drive.google.com/uc?id=1tZVAbTJRL_3wcKE_-8asBNOiBmy2Ypvl" },
        { id: 41, word: "Ratón", rimas: 42, syllable_separation: "ra-tón", image: "https://drive.google.com/uc?id=1wbcjITCtGlAX9BQ4XWUV2_Q8w4zCB-rw", audio: "https://drive.google.com/uc?id=1NjsBEUMUxPiffJqp6h-DpVzvPVGVNBAj", audioSilaba: "https://drive.google.com/uc?id=1gVzJA4_5xD7do4mSpR3BHqAzx44SfChM" },
        { id: 42, word: "Limón", rimas: 41, syllable_separation: "li-món", image: "https://drive.google.com/uc?id=1S_lUzcpEOcLX3nczt1SKCY2U3LOhCxTj" , audio: "https://drive.google.com/uc?id=1H6BcXu8hZmr-aogtblW7R9NkQhpbpT7s", audioSilaba: "https://drive.google.com/uc?id=1ecmiyaNpCAppZVIaNdCc5_G1CHgqwChi" },
        { id: 43, word: "Sol", rimas: 44, syllable_separation: "sol", image: "https://drive.google.com/uc?id=1R611kaajVepgToncebVpo0gYIFOAXa_I", audio: "https://drive.google.com/uc?id=1OFyQ7pQCqgMoUmS8zH47KAweZLflyXtV", audioSilaba: "https://drive.google.com/uc?id=10_t3hMPoJ9w6fTF6mzp94es-CBbrMEbZ" },
        { id: 44, word: "Girasol", rimas: 43, syllable_separation: "gi-ra-sol", image: "https://drive.google.com/uc?id=17RrMHsKyMn7JTSYjSa1B__IimvJ39BYQ", audio: "https://drive.google.com/uc?id=1vNjkxNNyu72-VsHMyKLAIdDzutFR20Yp", audioSilaba: "https://drive.google.com/uc?id=13eaKjbVDq0HKC1_LIRQ1XSQ9b2tB8CQQ" },
        { id: 45, word: "Sopa", rimas: 46, syllable_separation: "so-pa", image: "https://drive.google.com/uc?id=16-bY3XNRfCXm9nd_7yMAvb7mZ_uAnp-z", audio: "https://drive.google.com/uc?id=1O-y2MJgWzhIE2oC-5YfRBTHXwKe1sC6f", audioSilaba: "https://drive.google.com/uc?id=1vYGezIqIRDw_f43R7-07N2nSWqEvCVUY" },
        { id: 46, word: "Ropa", rimas: 45, syllable_separation: "ro-pa", image: "https://drive.google.com/uc?id=1T_xf3maYixnZpEquRqvdVFGZeGKNxQXE", audio: "https://drive.google.com/uc?id=1Y7InVVGSti-Nbee1iqYzs0bUtweXdKrD", audioSilaba: "https://drive.google.com/uc?id=1_94_ZSiSNmnpBPo9osqttIDI17WmpjZH" },
        { id: 47, word: "Veinte", rimas: 48, syllable_separation: "vein-te", image: "https://drive.google.com/uc?id=1sTd8NQaMIbIoFHyLkSrSf2Tgpai0q9vQ", audio: "https://drive.google.com/uc?id=1cMz9uDQoBItsMKYa2-F_FARTZZkIYN52", audioSilaba: "https://drive.google.com/uc?id=1kdH3mpgiPHoIq41kuQU6CM82hZMm8T7E" },
        { id: 48, word: "Diente", rimas: 47, syllable_separation: "dien-te", image: "https://drive.google.com/uc?id=1YPskbSlij4SKlbKnLPaAw96e5I7chwfE", audio: "https://drive.google.com/uc?id=1iqSlwZPlL7Nn2-WiBefvgCFP7DFhQNmH", audioSilaba: "https://drive.google.com/uc?id=1cVe4oqxNv61maL8NMi6hOFNkxHaVav_8" },
        { id: 49, word: "Ventana", rimas: 50, syllable_separation: "ven-ta-na", image: "https://drive.google.com/uc?id=1q3hhQniMj4_IzRQrZTxElUjV_qWmTNxa", audio: "https://drive.google.com/uc?id=1CP52blPufjHWLkFS2VAGC_iZVISgHK3W", audioSilaba: "https://drive.google.com/uc?id=1dlrshqJaIVY53pXid-XWYrrmzPfp7iAE" },
        { id: 50, word: "Iguana", rimas: 49, syllable_separation: "i-gua-na", image: "https://drive.google.com/uc?id=1sAHOOtuakI5T3i3aBzT8POh-5C6a_iux", audio: "https://drive.google.com/uc?id=15Y2aA5bnCKDF9XoBP5lGnc4-ozqenekf", audioSilaba: "https://drive.google.com/uc?id=1-XTwgveuvCq6UNarrOhnqH_eEc3dNEmV" },
    ];
};

export function getrhymingWords() {
    const palabras = wordsDataService();
    const idAleatorio = Math.floor(Math.random() * palabras.length);
    const palabraAleatoria = palabras[idAleatorio];

    const rima = palabras.find(word => word.id === palabraAleatoria.rimas);
    let idAleatorio2;
    do {
        idAleatorio2 = Math.floor(Math.random() * palabras.length);
    } while (idAleatorio2 === palabraAleatoria.rimas || idAleatorio2 === idAleatorio);

    const seleccionAleatoria = palabras[idAleatorio2];

    return {
        palabra: palabraAleatoria,
        rima,
        seleccionAleatoria,
    };
}


